name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'aws-region'
        required: true
        default: 'us-east-1'
      home:
        description: 'location'
        required: true
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"


# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Deploy To Prod

on: workflow_dispatch

jobs:
  deploy-to-prod-npm:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Prod
        run: echo "Hello World"
  error-out-if-not-main:
    if: github.ref != 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Error
        run: echo "You cannot deploy branches into PROD!"

