# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
name: Publish to NPM

on: 
  workflow_run:
    workflows: ["NPM Build"]

jobs:
  pre-checks:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps: 
      - name: This should fail!
        run: echo "You can only deploy main branches"; exit 1
  publish-npm-only-for-main:
    needs: pre-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
